// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CryBaby",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "CryBaby",
            targets: ["AppModule"],
            bundleIdentifier: "com.Puupy.bootcamp.CryBaby",
            teamIdentifier: "ADU9G6DNZ9",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coffee),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Cry analyzed needs to access your camera to record the hand tremor test video. Else you won't be able to do a hand tremor test."),
                .microphone(purposeString: "Cry analyzed needs to access your microphone to record for the speaking test. Else you won't be able to do a speaking test.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
